todo/todo/agenda/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from .views import CalendarioJsonListView, CalendarioView

urlpatterns = patterns(
    'todo.agenda.views',
    url(
        r'^calendario/json/$',
        CalendarioJsonListView.as_view(),
        name='calendario_json'
    ),
    url(
        r'^$',
        CalendarioView.as_view(),
        name='calendario'
    ),
    url(r'^evento/list/$', 'eventos', name='eventos'),
    url(r'^evento/meus/$', 'meus_eventos', name='meus_eventos'),
    url(r'^evento/form/$', 'evento_form', {'publico': False}, name='evento_form'),
    url(r'^evento/form/(?P<pk>\d+)/$', 'evento_form', {'publico': False}, name='evento_form'),
    url(r'^evento/participar/(?P<pk>\d+)/$', 'participar', name='evento_participar'),
    url(r'^evento/publico/form/$', 'evento_form', {'publico': True}, name='evento_publico_form'),
    url(r'^evento/publico/form/(?P<pk>\d+)/$', 'evento_form', {'publico': True}, name='evento_publico_form'),
    url(r'^evento/delete/(?P<pk>\d+)/$', 'evento_delete', name="evento_delete"),

    url(r'^departamento/list/$', 'departamento_list', name="departamento_list"),
    url(r'^departamento/form/$', 'departamento_create', name="departamento_form"),
    url(r'^departamento/form/(?P<pk>\d+)/$', 'departamento_update', name="departamento_form"),
    url(r'^departamento/delete/(?P<pk>\d+)/$', 'departamento_delete', name="departamento_delete"),
)

todo/todo/urls.py
# coding: utf-8
from django.conf.urls import include, patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.views import logout, login

from todo.core.forms import AuthenticationForm


urlpatterns = patterns(
    '',

    #url(r'^$', TemplateView.as_view(template_name='base.html')),
    url(r'^', include('todo.core.urls')),
    url(r'^', include('todo.agenda.urls')),

    # Logins
    url(r'^logout/$', logout, {"next_page": "/"}, name="logout"),
    url(
        r'^signin/$',
        login,
        {
            'template_name': 'login.html',
            'authentication_form': AuthenticationForm,
        },
        name="login"
    ),

    # password Reset
    url(
        r'^user/password/reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': '/user/password/reset/done/'},
        name="password_reset"
    ),
    url(
        r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done'
    ),
    url(
        r'^user/password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': '/user/password/done/'}
    ),
    url(
        r'^user/password/done/$',
        'django.contrib.auth.views.password_reset_complete'
    ),

    url(r'^user/activate/(?P<pk>\d+)/$', 'todo.core.views.user_activate', name="activate_user"),
    url(r'^user/deactivate/(?P<pk>\d+)/$', 'todo.core.views.user_deactivate', name="deactivate_user"),
    # url(r'^accounts/profile/', 'todo.core.views.profile_edit', name='profile_edit'),
)

todo/todo/agenda/models.py
# coding: utf-8

from django.db import models
from utils import datetime_to_timestamp

from todo.core.models import User


class CalendarioEvento(models.Model):
    TIPOS = (
        ('', 'Normal'),
        ('event-important', 'Importante'),
        ('event-info', 'Informativo'),
        ('event-inverse', 'Pausa'),
        ('event-special', 'Especial'),
        ('event-success', 'Completo'),
        ('event-warning', 'Cancelado'),
    )
    nome = models.CharField(max_length=255)
    tipo = models.CharField(max_length=15, choices=TIPOS)
    descricao = models.TextField(default='')
    inicio = models.DateTimeField(verbose_name=u'Início')
    fim = models.DateTimeField(verbose_name='Fim', null=True, blank=True)
    owner = models.ForeignKey(User, null=True, blank=True, related_name='owner')
    participantes = models.ManyToManyField(User, related_name='participantes')
    publico = models.BooleanField()

    @property
    def inicio_timestamp(self):
        return datetime_to_timestamp(self.inicio)

    @property
    def fim_timestamp(self):
        return datetime_to_timestamp(self.fim)

    def get_absolute_url(self):
        return '/evento/form/%d/' % self.pk

    def __unicode__(self):
        return self.nome


class Departamento(models.Model):
    nome = models.CharField(max_length=255)
    funcionarios = models.ManyToManyField(User, related_name='funcionarios')

    @classmethod
    def get_funcionarios_by_user_dpt(cls, user):
        dpts = cls.objects.filter(funcionarios__pk=user.pk)
        funs_pk = set()
        for dpt in dpts:
            for fun in dpt.funcionarios.all():
                funs_pk.add(fun.pk)
        return User.objects.filter(pk__in=list(funs_pk)).exclude(pk=user.pk)

    def __unicode__(self):
        return self.nome

todo/todo/agenda/forms.py
# coding: utf-8

from django import forms

from .models import CalendarioEvento
from todo.core.models import User
from todo.agenda.models import Departamento


class EventoForm(forms.ModelForm):
    def __init__(self, *args, **kw):
        user = kw.pop('user')
        self.user = user
        super(EventoForm, self).__init__(*args, **kw)
        self.fields['participantes'].queryset = User.objects.all().exclude(pk=user.pk)

        if not user.is_superuser:
            self.fields['participantes'].queryset = Departamento.get_funcionarios_by_user_dpt(user)

    def save(self, commit=True):
        instance = super(EventoForm, self).save(commit=False)
        instance.owner = self.user
        instance.publico = False
        if commit:
            instance.save()
        return instance

    class Meta:
        model = CalendarioEvento
        exclude = ['owner', 'publico']


class EventoPublicoForm(EventoForm):
    def __init__(self, *args, **kw):
        super(EventoPublicoForm, self).__init__(*args, **kw)
        self.fields['participantes'].queryset = User.objects.all().exclude(pk=self.user.pk)

    def save(self, commit=True):
        instance = super(EventoPublicoForm, self).save(commit=False)
        instance.publico = True
        if commit:
            instance.save()
        return instance

    class Meta(EventoForm.Meta):
        pass


class DepartamentoForm(forms.ModelForm):
    def __init__(self, *args, **kw):
        super(DepartamentoForm, self).__init__(*args, **kw)
        self.fields['funcionarios'].required = False

    class Meta:
        model = Departamento

todo/todo/agenda/views.py
# coding: utf-8
import datetime

from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import user_passes_test, login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseRedirect, Http404
from django.db.models import Q

from .models import CalendarioEvento, Departamento
from .serializers import evento_serializer
from .utils import timestamp_to_datetime
from .forms import EventoForm, DepartamentoForm, EventoPublicoForm


class CalendarioJsonListView(ListView):

    template_name = 'agenda/calendario_eventos.html'

    def get_queryset(self):
        if self.request.user.is_authenticated():
            queryset = CalendarioEvento.objects.filter(Q(owner=self.request.user) | Q(participantes=self.request.user))
        else:
            queryset = CalendarioEvento.objects.filter(publico=True)
        from_date = self.request.GET.get('from', False)
        to_date = self.request.GET.get('to', False)

        if from_date and to_date:
            queryset = queryset.filter(
                inicio__range=(
                    timestamp_to_datetime(from_date) + datetime.timedelta(-30),
                    timestamp_to_datetime(to_date)
                    )
            )
        elif from_date:
            queryset = queryset.filter(
                inicio__gte=timestamp_to_datetime(from_date)
            )
        elif to_date:
            queryset = queryset.filter(
                fim__lte=timestamp_to_datetime(to_date)
            )

        return evento_serializer(queryset)


class CalendarioView(TemplateView):

    template_name = 'agenda/calendario.html'


class EventosList(ListView):
    template_name = 'agenda/evento_list.html'

    def get_queryset(self):
        if self.request.user.is_authenticated():
            queryset = CalendarioEvento.objects.filter(participantes=self.request.user)
        else:
            queryset = CalendarioEvento.objects.filter(publico=True)
        return queryset


eventos = EventosList.as_view()


class MeusventosList(ListView):
    template_name = 'agenda/evento_list.html'

    def get_queryset(self):
        queryset = CalendarioEvento.objects.filter(owner=self.request.user)
        return queryset


meus_eventos = login_required(MeusventosList.as_view())


def participar(request, pk):
    evento = get_object_or_404(CalendarioEvento, pk=pk, publico=True)
    evento.participantes.add(request.user)
    return redirect(reverse_lazy('evento_form', kwargs={'pk': pk}))


def evento_form(request, publico=True, pk=None):
    template_name = 'agenda/evento.html'
    participante = False
    if pk:
        if request.user.is_authenticated():
            evento = get_object_or_404(CalendarioEvento, pk=pk)
            meu_evento = evento.owner == request.user
            participante = True
        else:
            evento = get_object_or_404(CalendarioEvento, pk=pk, publico=True)
            meu_evento = False
            participante = evento.participantes.filter(pk=request.pk).count() >= 1
    else:
        meu_evento = True
        evento = None
    context = {'evento': evento, 'publico': publico, 'participante': participante}

    if meu_evento:
        template_name = 'agenda/evento_form.html'
        if publico:
            action_url = 'evento_publico_form'
            form = EventoPublicoForm(request.POST or None, instance=evento, user=request.user)
        else:
            action_url = 'evento_form'
            form = EventoForm(request.POST or None, instance=evento, user=request.user)
        context['action_url'] = action_url
        if request.method == "POST":
            if form.is_valid():
                form.save()
                form.save_m2m()
                return redirect(reverse_lazy('meus_eventos'))
        context['form'] = form
    return render(
        request,
        template_name,
        context
    )


class EventoDeleteView(DeleteView):
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.owner != request.user:
            raise Http404

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def delete(self, request, *args, **kwargs):
        if self.object.owner != request.user:
            raise Http404
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())


evento_delete = user_passes_test(
    lambda u: u.is_superuser)(DeleteView.as_view(model=CalendarioEvento, template_name='confirm_delete.html', success_url=reverse_lazy('meus_eventos')))


departamento_create = user_passes_test(
    lambda u: u.is_superuser)(CreateView.as_view(form_class=DepartamentoForm, model=Departamento, success_url=reverse_lazy('departamento_list')))
departamento_delete = user_passes_test(
    lambda u: u.is_superuser)(DeleteView.as_view(model=Departamento, template_name='confirm_delete.html', success_url=reverse_lazy('departamento_list')))
departamento_list = user_passes_test(
    lambda u: u.is_superuser)(ListView.as_view(queryset=Departamento.objects.all(), paginate_by=10))
departamento_update = user_passes_test(
    lambda u: u.is_superuser)(UpdateView.as_view(form_class=DepartamentoForm, model=Departamento, success_url=reverse_lazy('departamento_list')))

todo/todo/agenda/templates/agenda/calendario.html
{% extends 'base.html' %} 
{% load calendario %}

{% block content %}
<div class="row-fluid">
    <div class="span12">
        <h3>Ano: <span id="ano"></span> Mês: <span id="mes"></span></h3>
        {% controls 'from-inline pull-right' %}
    </div>
</div>
<div class="clear-fix">
</div>
<div class="row">
    <div class="span7">
        {% calendario '' %}
    </div>
    <div class="span3">

    </div>
</div>
{% endblock %}

todo/todo/agenda/templates/agenda/calendario_eventos.html
{% autoescape off %} {{ object_list }} {% endautoescape %}

todo/todo/agenda/templates/agenda/departamento_form.html
{% extends "base.html" %}

{% load bootstrap3 %}


{% block title %}
    Formulário
{% endblock %}

{% block content %}
<form method="POST" action="{% if not form.instance.pk %}{% url 'departamento_form' %}{% else %}{% url 'departamento_form' pk=form.instance.pk %}{% endif %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="{% if not form.instance.pk %}Cadastrar{% else %}Alterar{% endif %}" class="btn btn-primary" />
    <input type="reset" value="Cancelar"  class="btn btn-warning" />
</form>
{% endblock %}

todo/todo/agenda/templates/agenda/departamento_list.html
{% extends 'base.html' %} 
{% load calendario %}

{% block content %}
<div class="row-fluid">
    <div class="span12">
    	<a href="{% url 'departamento_form' %}" class="btn btn-primary">Novo</a>
        <table class="table table-bordered table-striped">
		    <thead>
		        <tr>
		            <th>Departamento</th>
		            <th style="width: 60px;">deletar</th>
		        </tr>
		    </thead>
		    <tbody>
		        {% for dpt in object_list %}
		        <tr>
		            <td><a href="{% url 'departamento_form' dpt.pk %}">{{ dpt.nome }}</a></td>
		            <td>
		                <a href="{% url 'departamento_delete' dpt.pk %}" class="btn btn-small btn-danger">
		                    X
		                </a>
		            </td>
		        </tr>
		        {% endfor %}
		    </tbody>
		</table>
		<div class="pagination">
		    <span class="step-links">
		        {% if page_obj.has_previous %}
		            <a href="?page={{ page_obj.previous_page_number }}">anterior</a>
		        {% endif %}

		        <span class="current">
		            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
		        </span>

		        {% if page_obj.has_next %}
		            <a href="?page={{ page_obj.next_page_number }}">próximo</a>
		        {% endif %}
		    </span>
		</div>
    </div>
</div>

{% endblock %}

todo/todo/agenda/templates/agenda/evento.html
{% extends 'base.html' %} 
{% load calendario %}

{% block content %}
<div class="row-fluid">
    <div class="span12">
        {% if evento.publico %}
        {% if not participante %}
            <a href="{% url 'evento_participar' evento.pk %}" class="btn btn-primary">Participar</a>
        {% endif %}
        {% endif %}
        <table>
        	<tr>
        		<td>Nome:</td>
        		<td>{{ evento.nome }}</td>
        	</tr>
        	<tr>
        		<td>Tipo:</td>
        		<td>{{ evento.get_tipo_display }}</td>
        	</tr>
        	<tr>
        		<td>Início:</td>
        		<td>{{ evento.inicio|default:"---" }}</td>
        	</tr>
        	<tr>
        		<td>Fim:</td>
        		<td>{{ evento.fim|default:"---" }}</td>
        	</tr>
        	<tr>
        		<td>Público:</td>
        		<td>{{ evento.tipo|yesno:"Sim,Não" }}</td>
        	</tr>
        	<tr>
        		<td colspan="2">Participantes</td>
        	</tr>
        	{% for p in evento.participantes.all %}
	        	<tr>
	        		<td colspan="2">{{ p }}</td>
	        	</tr>
	        {% empty %}
	        	<tr>
	        		<td colspan="2">Nenhum Participante</td>
	        	</tr>
        	{% endfor %}
        </table>
    </div>
</div>
{% endblock %}

todo/todo/agenda/templates/agenda/evento_form.html
{% extends 'base.html' %} 
{% load static %}
{% load bootstrap3 %}

{% block content %}
<div class="row-fluid">
    <div class="span12">
        <h3>Novo Evento{% if publico %} Público{% endif %}</h3>
        <form method="POST" action="{% if form.instance.pk %}{% url action_url form.instance.pk %}{% else %}{% url action_url %}{% endif %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary" value="{% if not form.instance.pk %}Cadastrar{% else %}Alterar{% endif %}" />
            <input type="reset" value="Cancelar"  class="btn btn-warning" />
        </form>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/mask.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(function($){
       $("#id_inicio").mask(
            "99/99/9999 99:99:99",
            {
                placeholder:"dd/mm/aaaa hh:mm:ss"
            }
        );
       $("#id_fim").mask(
            "99/99/9999 99:99:99",
            {
                placeholder:"dd/mm/aaaa hh:mm:ss"
            }
        );
    });
</script>
{% endblock %}

todo/todo/agenda/templates/agenda/evento_list.html
{% extends 'base.html' %} 
{% load calendario %}

{% block content %}
<div class="row-fluid">
    <div class="span12">
        {% if request.user.is_authenticated %}
            <a href="{% url 'evento_form' %}" class="btn btn-primary">Novo Evento</a>
        {% endif %}
        {% if request.user.is_authenticated %}
            <a href="{% url 'evento_publico_form' %}" class="btn btn-primary">Novo Evento Público</a>
        {% endif %}
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Eventos</th>
                    <th style="width: 60px;">deletar</th>
                </tr>
            </thead>
            <tbody>
                {% for evt in object_list %}
                <tr>
                    <td><a href="{% url 'evento_form' evt.pk %}">{{ evt.nome }}</a></td>
                    <td>
                        <a href="{% url 'evento_delete' evt.pk %}" class="btn btn-small btn-danger">
                            X
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if   .has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">anterior</a>
                {% endif %}

                <span class="current">
                    Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">próximo</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>

{% endblock %}